# Generated by Django 2.2.3 on 2019-08-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=255, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('idade', models.DateTimeField(max_length=255, verbose_name='Idade')),
                ('data_de_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True, verbose_name='Nome de ideia')),
                ('descricao', models.TextField(verbose_name='Descreva sua ideia')),
                ('data', models.DateTimeField(max_length=255, verbose_name='Data')),
                ('data_de_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_de_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('pessoa', models.ForeignKey(on_delete=None, to='funcionalidades.Pessoa')),
            ],
        ),
    ]
