# Generated by Django 2.2.3 on 2019-08-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionalidades', '0002_pessoa_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='senha',
            field=models.CharField(max_length=255, null=True, verbose_name='senha'),
        ),
    ]
