# Generated by Django 2.2.3 on 2019-08-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionalidades', '0005_auto_20190804_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='idade',
            field=models.CharField(max_length=255, verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='senha',
            field=models.CharField(default=' ', max_length=10, verbose_name='senha'),
            preserve_default=False,
        ),
    ]
