# Generated by Django 2.2.3 on 2019-08-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionalidades', '0006_auto_20190804_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='senha',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
